---
- name: Install web-server
  hosts: all
  become: yes

  tasks:

  - name: install
    yum: name=httpd state=latest
  
  - name: start Apache and enable it on the boot
    service: name=httpd state=started enabled=yes